// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/nikita-itmo-gh-acc/car_estimator_authorization/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ISessionSaver is an autogenerated mock type for the ISessionSaver type
type ISessionSaver struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, session, expiresIn
func (_m *ISessionSaver) Save(ctx context.Context, session *domain.Session, expiresIn time.Duration) (string, error) {
	ret := _m.Called(ctx, session, expiresIn)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session, time.Duration) (string, error)); ok {
		return rf(ctx, session, expiresIn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Session, time.Duration) string); ok {
		r0 = rf(ctx, session, expiresIn)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Session, time.Duration) error); ok {
		r1 = rf(ctx, session, expiresIn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewISessionSaver creates a new instance of ISessionSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISessionSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISessionSaver {
	mock := &ISessionSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
