// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/nikita-itmo-gh-acc/car_estimator_authorization/domain"
	mock "github.com/stretchr/testify/mock"
)

// IUserSaver is an autogenerated mock type for the IUserSaver type
type IUserSaver struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, user
func (_m *IUserSaver) Save(ctx context.Context, user domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIUserSaver creates a new instance of IUserSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserSaver {
	mock := &IUserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
